language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - yarn test --ci --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
